### ISSUE TITLE
mangling underscore as an argument

### ISSUE THREAD

**Issue by Gruruya** [disruptek/openapi#7]
Needs some new name-mangling, currently compiling [disruptek/github](https://github.com/disruptek/github) with Nim devel errors with:
```sh
Error: undeclared identifier: '_'
```
Error was introduced with nim-lang/Nim@05c6db6500de0551882a2d6cc612c9afb6ca674c
Manually replacing everywhere _ is used as an argument with another name fixes the error.

**Comment by disruptek** [comment]
Yeah, it's annoying.  Not sure when I will have time to fix it, but do you have a suggestion for what to change the argument name to?  Obviously, it needs to be clash-free with virtually any keyword argument that might be present in any API. :roll_eyes:

**Comment by Gruruya** [comment]
You could use was_an_underscore_ID, mangled or mg_underscore_ID, underscore_par/prm_ID. Pretty much any prefix or suffx with "underscore" would work. None of my suggestions showed any results on github code search.

**Comment by disruptek** [comment]
Let's just major it and rename the argument to `content` or somesuch.

**Comment by Gruruya** [comment]
ya sure

**Comment by disruptek** [comment]
Closed in 65f77486593e27cfd85f622b7eb04ce25af28885
